language: go

go: 1.10.x

matrix:
  include:
    - go: 1.10.x
      env: COVERAGE=true
    - go: 1.9.x
      env: COVERAGE=false

install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - ./travis.sh

env:
  global:
    secure: "Qik49IM2LDIIU8xWB2oSp1Qj21GYM00ViMUN/g43o99mMOgvDAkkd+bpG1nuI6g5+ypxKWdXPNY0g0G4VrxYstfiXbLTuRvjnclCU8jHToluz6RSPajhveNjFEVaxEbNArxEbIaPCQRRSpfTPb3ray3lX0z69Z33b15PFXi99PTtC1RwkNTHnmB9Rt35bjctXkL26OINnsQEf6EyFl6q6wU4cC4+R5tjQVEBMGhEuTj0zIB/rgebsq0yBlLqm4a32LH+ye1vc3+2d1mwM5YDcuKKrypLhELCFdAqAk1fNZ3rkqZsZ+X50LgzD/ePKzat+UDV3qQmfzhDHCLQP6uxiU/Edy+H2pFR91avcpNKwby5LHPVxjJs0RCFz9gtP3LxUcAsa676AuXhTjlfU1Dz9H23KchIFuP893JpEjhX0NtF/OvsjiaTCnTshQWlk/Y13oip0Ln0d6zwQNiqjSY2ttVSdN0Zr6b2V7OBXfqmjYOBpc90rcz/sWpK4xo17kCGYBeEa3oggrIGKkJqr9jSr1J8/4HZ43DO6w+FintLRfJLlm9UlTsHJ66rY/D6LKCJhyNDIeLQDN23HyNL9mecV3AbdoefTg6bj8Wkb73MAdlMqNgL9Qpjxf7J8xKaNc7bvfsnIf4/YaYNVCnnHtZZljtD4o+UnfiBpdNEzEQ5qQs="
